### ISSUE TITLE
Use a config file for aws creds or read them from an existing ~/.aws dir used for aws cli

### ISSUE THREAD

**Issue by geekpete** [eschwim/s3wipe#10]
Avoid having credentials used as cli parameters that will potentially be stored in shell history presenting a security risk.

Have the option to use a config file or fetch creds from any existing aws cli ~/.aws dir configs 
https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html

**Comment by geekpete** [comment]
Or does boto handle this already?

**Comment by matschaffer** [comment]
Haven't confirmed if `~/.aws/credentials` work, but env vars do so would bet this is closable.

**Comment by mikelorant** [comment]
Can confirm this already works.
